defaults: &defaults
  working_directory: /go/src/github.com/sbstjn/appsync-router
  docker:
    - image: circleci/golang:1.8

version: 2

releases: &releases
  filters:
    tags:
      only: /v[0-9]+(\.[0-9]+)*/
    branches:
      ignore: /.*/

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Gopkg.toml" }}

      - run:
          name: Install dependencies
          command: |
            go get -u github.com/golang/dep/...
            dep ensure

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Gopkg.toml" }}
          paths:
            - "vendor"

      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Run tests
          command: make test

      - persist_to_workspace:
          root: .
          paths:
            - .

  coverage:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Install goveralls
          command: go get github.com/mattn/goveralls

      - run:
          name: Update Coveralls.io
          command: make coveralls

workflows:
  version: 2

  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - coverage:
          require:
            - coverage
  release:
    jobs:
      - checkout:
          <<: *releases
      - test:
          <<: *releases
          requires:
            - checkout
      - coverage:
          <<: *releases
          requires:
            - test